language: python
cache: pip
matrix:
  include:
  - python: '3.7'
    dist: xenial
    sudo: true
install:
- pip install -r requirements-test.txt
script:
- bash test.sh --noinstall --no-update --novirtualenv --strict